# Dockerfile.cypress
FROM cypress/included:12.17.4

# Set working directory
WORKDIR /e2e

# Copy Cypress configuration and tests
COPY cypress/ ./cypress/
COPY cypress.json ./

# Default command
CMD ["cypress", "run"]