# badminton_court/postal-compose.yml

services:
  postal:
    container_name: postal
    build:
      context: .
      dockerfile: Dockerfile.postal
    ports:
      - "5000:5000"  # Postal Web UI
      - "465:465"    
      - "25:25"
      - "587:587"
    environment:
      - RAILS_ENV=production
      - POSTAL_HOST=${POSTAL_HOST}
      - POSTAL_PASSWORD=${POSTAL_PASSWORD}
      - POSTAL_PORT=${POSTAL_PORT}
      # Postal DB configuration using environment variables:
      - DB_HOST=${POSTAL_DB_HOST}
      - DB_PORT=${POSTAL_DB_PORT}
      - DB_USER=${POSTAL_DB_USER}
      - DB_PASS=${POSTAL_DB_PASS}
      - DB_NAME=${POSTAL_DB_NAME}
      - MSG_DB_HOST=${MSG_DB_HOST}
      - MSG_DB_PORT=${MSG_DB_PORT}
      - MSG_DB_USER=${MSG_DB_USER}
      - MSG_DB_PASS=${MSG_DB_PASS}
      - MSG_DB_NAME=${MSG_DB_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_CERT_PATH=${SMTP_CERT_PATH}
      - SMTP_KEY_PATH=${SMTP_KEY_PATH}
      - SIGNING_KEY_PATH=${SIGNING_KEY_PATH}
    depends_on:
      - mariadb
      - redis
    volumes:
      - postal_data:/postal/data
      - ./config/postal.yml:/opt/postal/config/postal.yml
      - ./certs:/postal/config/tls 

  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${POSTAL_DB_NAME}
      MYSQL_USER: ${POSTAL_DB_USER}
      MYSQL_PASSWORD: ${POSTAL_DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

volumes:
  postal_data:
  mariadb_data: