# Generated by Django 5.2.6 on 2026-05-05 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit – unique product code', max_length=50, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='UPC/EAN barcode', max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='piece', help_text='Unit of measure: piece, box, tube, set', max_length=20)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10, help_text='Low‑stock threshold')),
                ('reorder_quantity', models.IntegerField(default=20, help_text='Suggested order quantity when restocking')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Average cost per unit', max_digits=10)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Retail selling price (if applicable)', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='Storage location: Store Room A, Court 1 Cabinet', max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], default='new', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False if discontinued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.inventorycategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In (Purchase/Return)'), ('out', 'Stock Out (Sale/Transfer)'), ('consumed', 'Consumed (Court usage)'), ('damaged', 'Damaged / Lost'), ('adjustment', 'Adjustment (Inventory count correction)')], max_length=15)),
                ('quantity', models.IntegerField(help_text='Positive = added, negative = removed; sign auto‑adjusted')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of transaction', max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, help_text="E.g., Booking #123, Event 'Summer Cup', or Invoice #INV-001", max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
