# Generated by Django 5.2.6 on 2025-10-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('view_all_bookings', 'Can view all bookings'), ('manage_any_booking', 'Can manage any booking'), ('cancel_any_booking', 'Can cancel any booking'), ('process_any_payment', 'Can process any payment')]},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'permissions': [('view_all_courts', 'Can view all courts'), ('manage_court_info', 'Can manage court information'), ('manage_court_schedules', 'Can manage court schedules')]},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_all_customers', 'Can view all customers'), ('manage_customer_accounts', 'Can manage customer accounts')]},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_all_employees', 'Can view all employees'), ('manage_employee_info', 'Can manage employee information'), ('manage_employee_schedules', 'Can manage employee schedules'), ('view_payroll_info', 'Can view payroll information'), ('process_payroll', 'Can process payroll')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('view_all_payments', 'Can view all payments'), ('manage_any_payment', 'Can manage any payment'), ('process_refunds', 'Can process refunds')]},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'permissions': [('view_all_time_entries', 'Can view all time entries'), ('manage_any_time_entry', 'Can manage any time entry'), ('use_time_clock', 'Can use time clock system')]},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'permissions': [('view_all_schedules', 'Can view all work schedules'), ('manage_any_schedule', 'Can manage any work schedule')]},
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
